version: '3'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - change-app-network

  # Backend service
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: change-app-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/changeapp
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
    networks:
      - change-app-network

  # Frontend service
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: change-app-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - change-app-network

networks:
  change-app-network:
    driver: bridge

volumes:
  mongodb_data:
